#!/bin/bash

# Worker script for all (ordinary) sites.

if [ $# -ne 7 ]; then
  echo "usage: $0 <host> <port> <user> <identity> <user-agent> <URL> <timeout>"
  exit 1
fi

host=$1
port=$2
user=$3
identity=$4
agent=$5
url=$6
timeout=$7

remote_cmd="curl -A \"$agent\" -ksiL \"$url\""
cmd="ssh -o StrictHostKeyChecking=no -i $identity -p $port $user@$host $remote_cmd"

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
$DIR/timeout -t $timeout $cmd

