#!/bin/bash

# Heartbeat script.

if [ $# -ne 5 ]; then
  echo "usage: $0 <host> <port> <user> <identity> <timeout>"
  exit 1
fi

host=$1
port=$2
user=$3
identity=$4
timeout=$5

remote_cmd="curl --version"
cmd="ssh -o StrictHostKeyChecking=no -i $identity -p $port $user@$host $remote_cmd"

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
$DIR/timeout -t $timeout $cmd

